import { renderProjectionText } from "../../../hooks/catalog.mjs";
import fs from "node:fs";
const codexPluginDisk = fs.readFileSync("hooks/hooks.json", "utf8");
const claudePluginDisk = fs.readFileSync("hooks/claude-hooks.json", "utf8");
console.log("codex-plugin render==disk:", renderProjectionText("codex") === codexPluginDisk);
console.log("claude render==disk:", renderProjectionText("claude") === claudePluginDisk);
const OLD = '"Edit|Write|MultiEdit|Bash|Read|Glob|Grep"';
const NEW = '"apply_patch|Edit|Write|MultiEdit|Bash|Read|Glob|Grep"';
const hardenedClaude = claudePluginDisk.replace(OLD, NEW);
const hardenedCodexPlugin = codexPluginDisk.replace(OLD, NEW);
console.log("apply_patch-hardened claude == committed claude:", hardenedClaude === claudePluginDisk, "(false => claude-hooks.json bytes change)");
console.log("apply_patch-hardened codex-plugin == committed codex-plugin:", hardenedCodexPlugin === codexPluginDisk, "(false => hooks.json bytes change)");
