#!/usr/bin/env node
// Generator for the two committed plugin skill-route trees (D9 LOCKED
// topology, slice-3 rev3, cell cnr2-12):
//
//   .claude-plugin/skills/ = render(canonical skills/, "claude")
//   .codex-plugin/skills/  = render(canonical skills/, "codex")
//
// Both trees are generated ONLY through the cnr2-9 renderer
// (renderSkillBytes) — never hand-copied. Package-time rendering was
// REJECTED (decision logged): these trees are committed, inspectable, and
// regenerated by re-running this script whenever canonical skills/ content
// changes. Today no skill file carries a runtime marker, so both trees are
// byte-identical to skills/ — no visible change, machinery + proof only.
//
// Whole-tree marker grammar is validated BEFORE any write (mirrors
// onboard_bee.mjs's validateSkillTreeMarkers): a malformed marker anywhere
// refuses the entire regeneration with zero writes.

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

import {
  renderSkillBytes,
  validateSkillMarkers,
  RENDER_RUNTIMES,
  RENDER_SIDECAR,
  buildRenderSidecar,
} from "../skills/bee-hive/scripts/onboard_bee.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(__dirname, "..");
const SOURCE_ROOT = path.join(REPO_ROOT, "skills");
const SKILL_DIR_RE = /^bee-/;

export const TARGET_ROOTS = {
  claude: path.join(REPO_ROOT, ".claude-plugin", "skills"),
  codex: path.join(REPO_ROOT, ".codex-plugin", "skills"),
};

function listBeeSkillDirs() {
  return fs
    .readdirSync(SOURCE_ROOT, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.isSymbolicLink() && SKILL_DIR_RE.test(entry.name))
    .map((entry) => entry.name)
    .sort();
}

// Walk one skill dir under SOURCE_ROOT. A symlink anywhere refuses loudly —
// mirrors onboard_bee.mjs's walkSkillTree symlink discipline (a symlinked
// skill dir is plausibly a live checkout; never write through it).
function walkFiles(dir, relPrefix = "") {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const rel = relPrefix ? `${relPrefix}/${entry.name}` : entry.name;
    const abs = path.join(dir, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`render_plugin_skill_trees: symlink forbidden in skill source: ${abs}`);
    }
    if (entry.isDirectory()) {
      out.push(...walkFiles(abs, rel));
    } else if (entry.isFile()) {
      out.push({ rel, abs });
    } else {
      throw new Error(`render_plugin_skill_trees: unsupported entry: ${abs}`);
    }
  }
  return out;
}

/** Every canonical bee-* skill file as [{ skillRel, abs }], sorted. */
export function canonicalFiles() {
  const files = [];
  for (const name of listBeeSkillDirs()) {
    for (const { rel, abs } of walkFiles(path.join(SOURCE_ROOT, name))) {
      files.push({ skillRel: `${name}/${rel}`, abs });
    }
  }
  return files;
}

/** Whole-tree marker grammar gate: non-empty means refuse, zero writes. */
export function validateWholeTree(files) {
  const errors = [];
  for (const { skillRel, abs } of files) {
    const text = fs.readFileSync(abs, "utf8");
    for (const e of validateSkillMarkers(text)) errors.push(`${skillRel}: ${e}`);
  }
  return errors;
}

/** render(canonical, runtime) as a Map<skillRel, Buffer>. */
export function renderTree(runtime, files) {
  const rendered = new Map();
  for (const { skillRel, abs } of files) {
    rendered.set(skillRel, renderSkillBytes(fs.readFileSync(abs), runtime));
  }
  return rendered;
}

// rendered: Map<"skillName/relPath", Buffer> (renderTree's output) -> one
// buildRenderSidecar entry per skill: {name, files: Map<relPath, sha256hex>}.
// Per-file hashes are sha256 of the RENDERED bytes already produced by
// renderTree, so the sidecar reflects exactly what writeTree is about to put
// on disk for this runtime (D7/D9).
function groupRenderedBySkill(rendered) {
  const bySkill = new Map();
  for (const [skillRel, bytes] of rendered) {
    const slash = skillRel.indexOf("/");
    const name = skillRel.slice(0, slash);
    const rel = skillRel.slice(slash + 1);
    if (!bySkill.has(name)) bySkill.set(name, new Map());
    bySkill.get(name).set(rel, crypto.createHash("sha256").update(bytes).digest("hex"));
  }
  return [...bySkill.entries()].map(([name, files]) => ({ name, files }));
}

export function sidecarObject(runtime, rendered) {
  return buildRenderSidecar(runtime, groupRenderedBySkill(rendered));
}

export function sidecarBytes(runtime, rendered) {
  return Buffer.from(`${JSON.stringify(sidecarObject(runtime, rendered), null, 2)}\n`, "utf8");
}

function writeTree(targetRoot, rendered, runtime) {
  fs.rmSync(targetRoot, { recursive: true, force: true });
  for (const [rel, bytes] of rendered) {
    const dest = path.join(targetRoot, ...rel.split("/"));
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, bytes);
  }
  fs.writeFileSync(path.join(targetRoot, RENDER_SIDECAR), sidecarBytes(runtime, rendered));
}

function main() {
  const files = canonicalFiles();
  const errors = validateWholeTree(files);
  if (errors.length) {
    console.error(`render_plugin_skill_trees: refused (marker grammar):\n${errors.join("\n")}`);
    process.exit(1);
  }
  for (const runtime of RENDER_RUNTIMES) {
    const rendered = renderTree(runtime, files);
    writeTree(TARGET_ROOTS[runtime], rendered, runtime);
    console.log(
      `WROTE ${path.relative(REPO_ROOT, TARGET_ROOTS[runtime])}: ${rendered.size} file(s) + ${RENDER_SIDECAR}`,
    );
  }
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) main();
